server:
  port: 8085
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/movieapp
    username: postgres
    password: makangratis
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: none  # Change back to none when using Flyway
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    table: flyway_schema_history_auth
    locations: classpath:db/migrations
    baseline-on-migrate: true
    validate-on-migrate: false  # Change to false initially
    clean-disabled: false  # Change to false for development
    baseline-version: 1
    encoding: UTF-8
    placeholder-replacement: false

# Add logging to see what's happening
logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.boot.autoconfigure.flyway: DEBUG

jwt:
  secret: your-secret-key-here-make-it-long-and-random
  access:
    expiration: 900000 # 15 minutes
  refresh:
    expiration: 604800000 # 7 days
    rotation:
      enabled: true
      max-rotations: 5
