server:
  port: 8082
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/movieapp
    username: postgres
    password: makangratis
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000 # Maximum time to wait for a connection from the pool ( 20 seconds )
      maximum-pool-size: 10 # Maximum number of connections in the pool
      minimum-idle: 5 # Minimum number of idle connections maintained
      idle-timeout: 300000 # Maximum time a connection can sit idle ( 5 min )
      max-lifetime: 1200000 # Maximum lifetime of a connection in the pool ( 20 min )
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    locations: db/migration
    clean-disabled: false
