ALTER TABLE tb_roles
ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_user_roles
ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_refresh_tokens
ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_password_reset_tokens
ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_email_verification_tokens
ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tb_login_attempts
ADD created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
ADD updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
