spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: 
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - HEAD
            allowedHeaders: "*"
            exposedHeaders:
              - Content-Length
              - Content-Range
              - Accept-Ranges
              - Content-Type
              - Authorization
            allowCredentials: false
      routes:
        - id: movie-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/movies/**
        - id: auth-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/auth/**
# JWT Configuration (same secret as auth-service)
jwt:
  secret: ${JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkw}

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.gugugaga.gateway: DEBUG