spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/movies/**
        - id: auth-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/auth/**
