spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: movie-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/movies/**
        - id: auth-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/auth/**
# JWT Configuration (same secret as auth-service)
jwt:
  secret: ${JWT_SECRET:YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY3ODkw}

# Logging
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.gugugaga.gateway: DEBUG